name: Take screenshots

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Oxipng
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo
      - name: Install Oxipng if it is not installed
        run: |
          which oxipng || cargo install oxipng
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright
      - name: Install dependencies
        run: |
          pip install shot-scraper
          shot-scraper install
      - name: Take shots
        run: |
          today=$(date +"%Y-%m-%d")
          shot-scraper https://hazadus.ru/ --width 1280 --wait 10000 -o "./screenshots/hazadus-ru.$today.png" && \
          shot-scraper https://hazadus.ru/blogroll/ --width 1280 --wait 10000 -o "./screenshots/hazadus-ru-blogroll.$today.png" && \
          shot-scraper http://hazadus.ru/microblog/ --width 1280 --wait 10000 -o "./screenshots/hazadus-ru-microblog.$today.png" && \
          shot-scraper https://anvlink.ru/ --width 1280 --wait 1000 -o "./screenshots/anvlink-ru.$today.png" && \
          shot-scraper http://nameapp.anverali.tech/ --width 1280 --wait 5000 -o "./screenshots/nameapp.$today.png" && \
          shot-scraper https://speakers24.ru/ --width 1280 --wait 1000 -o "./screenshots/speakers24-ru.$today.png" && \
          shot-scraper https://hazadus.github.io/knowledge/ --width 1280 --wait 2000 -o "./screenshots/knowdledge.$today.png" && \
          shot-scraper https://github.com/hazadus/ --width 1280 --wait 5000 -o "./screenshots/github-hazadus.$today.png"
      - name: Optimize PNGs
        run: |-
          oxipng -o 4 -i 0 --strip safe ./screenshots/*.png
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Скриншоты от ${timestamp}" || exit 0
          git pull --rebase
          git push
